version = "1.0"
i18n = "domain_config"

[feature]
name = "Features"

    [feature.portal]
    # Only available for "topest" domains
    name = "Portal"

        [feature.portal.show_other_domains_apps]
        type = "boolean"
        default = false

        [feature.portal.portal_title]
        type = "string"
        default = "YunoHost"

        [feature.portal.portal_logo]
        type = "file"
        accept = ["image/png", "image/jpeg", "image/svg+xml"]
        mode = "python"
        bind = "/usr/share/yunohost/portal/customassets/{filename}{ext}"

        [feature.portal.portal_theme]
        type = "select"
        choices = ["system", "light", "dark", "cupcake", "bumblebee", "emerald", "corporate", "synthwave", "retro", "cyberpunk", "valentine", "halloween", "garden", "forest", "aqua", "lofi", "pastel", "fantasy", "wireframe", "black", "luxury", "dracula", "cmyk", "autumn", "business", "acid", "lemonade", "night", "coffee", "winter"]
        default = "system"

        [feature.portal.search_engine]
        type = "url"
        default = ""

        [feature.portal.search_engine_name]
        type = "string"
        visible = "search_engine"

        [feature.portal.portal_user_intro]
        type = "text"

        [feature.portal.portal_public_intro]
        type = "text"

        # FIXME link to GCU

    [feature.app]
        [feature.app.default_app]
        type = "app"
        filter = "is_webapp"
        default = "_none"
        add_yunohost_portal_to_choices = true

    [feature.mail]
    name = "Email"

        [feature.mail.mail_out]
        type = "boolean"
        default = 1

        [feature.mail.mail_in]
        type = "boolean"
        default = 1

[dns]
name = "DNS"

    [dns.registrar]
    # This part is automatically generated in DomainConfigPanel

[cert]
name = "Certificate"

    [cert.cert]

        [cert.cert.cert_summary]
        type = "alert"
        # Automatically filled by DomainConfigPanel

        [cert.cert.cert_validity]
        type = "number"
        readonly = true
        visible = "false"
        # Automatically filled by DomainConfigPanel

        [cert.cert.cert_issuer]
        type = "string"
        visible = false
        # Automatically filled by DomainConfigPanel

        [cert.cert.acme_eligible]
        type = "boolean"
        visible = false
        # Automatically filled by DomainConfigPanel

        [cert.cert.acme_eligible_explain]
        type = "alert"
        style = "warning"
        visible = "acme_eligible == false || acme_eligible == null"

        [cert.cert.cert_no_checks]
        type = "boolean"
        default = false
        visible = "acme_eligible == false || acme_eligible == null"

        [cert.cert.cert_install]
        type = "button"
        icon = "star"
        style = "success"
        visible = "cert_issuer != 'letsencrypt'"
        enabled = "acme_eligible || cert_no_checks"

        [cert.cert.cert_renew]
        type = "button"
        icon = "refresh"
        style = "warning"
        visible = "cert_issuer == 'letsencrypt'"
        enabled = "acme_eligible || cert_no_checks"
