version = "1.0"
i18n = "domain_config"

#
# Other things we may want to implement in the future:
#
# - maindomain handling
# - autoredirect www in nginx conf
# - ?
#

[feature]
name = "Features"

    [feature.app]
        [feature.app.default_app]
        type = "app"
        filter = "is_webapp"
        default = "_none"

    [feature.mail]
    #services = ['postfix', 'dovecot']

        [feature.mail.features_disclaimer]
        type = "alert"
        style = "warning"
        icon = "warning"

        [feature.mail.mail_out]
        type = "boolean"
        default = 1

        [feature.mail.mail_in]
        type = "boolean"
        default = 1

        #[feature.mail.backup_mx]
        #type = "tags"
        #default = []
        #pattern.regexp = '^([^\W_A-Z]+([-]*[^\W_A-Z]+)*\.)+((xn--)?[^\W_]{2,})$'
        #pattern.error = "pattern_error"

    [feature.xmpp]

        [feature.xmpp.xmpp]
        type = "boolean"
        default = 0

[dns]
name = "DNS"

    [dns.registrar]
    # This part is automatically generated in DomainConfigPanel

#   [dns.advanced]
#
#        [dns.advanced.ttl]
#        type = "number"
#        min = 0
#        default = 3600


[cert]
name = "Certificate"

    [cert.cert]

        [cert.cert.cert_summary]
        type = "alert"
        # Automatically filled by DomainConfigPanel

        [cert.cert.cert_validity]
        type = "number"
        readonly = true
        visible = "false"
        # Automatically filled by DomainConfigPanel

        [cert.cert.cert_issuer]
        type = "string"
        visible = false
        # Automatically filled by DomainConfigPanel

        [cert.cert.acme_eligible]
        type = "boolean"
        visible = false
        # Automatically filled by DomainConfigPanel

        [cert.cert.acme_eligible_explain]
        type = "alert"
        style = "warning"
        visible = "acme_eligible == false || acme_elligible == null"

        [cert.cert.cert_no_checks]
        ask = "Ignore diagnosis checks"
        type = "boolean"
        default = false
        visible = "acme_eligible == false || acme_elligible == null"

        [cert.cert.cert_install]
        type = "button"
        icon = "star"
        style = "success"
        visible = "issuer != 'letsencrypt'"
        enabled = "acme_eligible || cert_no_checks"

        [cert.cert.cert_renew]
        type = "button"
        icon = "refresh"
        style = "warning"
        visible = "issuer == 'letsencrypt'"
        enabled = "acme_eligible || cert_no_checks"
