name: Check / auto apply Black

on:
  push:
    branches: [ "dev" ]

jobs:
  black:
    name: Check / auto apply black
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Check files using the black formatter
        uses: psf/black@stable
        id: black
        with:
          options: "."
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit-message: ":art: Format Python code with Black"
