.build-stage:
  stage: build
  needs:
    - job: actionsmap
    - job: invalidcode311
  image: "build-and-lint"
  variables:
    YNH_SOURCE: "https://github.com/yunohost"
    YNH_DEBIAN: "bookworm"
  before_script:
    - mkdir -p $YNH_BUILD_DIR
    - DEBIAN_FRONTEND=noninteractive apt update
  artifacts:
    paths:
      - ./*.deb

.build_script: &build_script
  - DEBIAN_FRONTEND=noninteractive apt --assume-yes -o Dpkg::Options::="--force-confold" install devscripts --no-install-recommends
  - cd $YNH_BUILD_DIR/$PACKAGE
  - git status || true
  - git log -n 1 || true
  - VERSION=$(dpkg-parsechangelog -S Version 2>/dev/null)
  - VERSION_NIGHTLY="${VERSION}+$(date +%Y%m%d%H%M)"
  - dch --package "${PACKAGE}" --force-bad-version -v "${VERSION_NIGHTLY}" -D "unstable" --force-distribution "Daily build."
  - debuild --no-lintian -us -uc
  - cp $YNH_BUILD_DIR/*.deb ${CI_PROJECT_DIR}/
  - cd ${CI_PROJECT_DIR}

########################################
# BUILD DEB
########################################

build-yunohost:
  extends: .build-stage
  variables:
    PACKAGE: "yunohost"
  script:
    - git ls-files | xargs tar -czf archive.tar.gz
    - mkdir -p $YNH_BUILD_DIR/$PACKAGE
    - cat archive.tar.gz | tar -xz -C $YNH_BUILD_DIR/$PACKAGE
    - rm archive.tar.gz
    - DEBIAN_FRONTEND=noninteractive apt --assume-yes -o Dpkg::Options::="--force-confold" build-dep $YNH_BUILD_DIR/$PACKAGE
    - *build_script

build-ssowat:
  extends: .build-stage
  variables:
    PACKAGE: "ssowat"
  script:
    - git clone $YNH_SOURCE/$PACKAGE -b $CI_COMMIT_REF_NAME $YNH_BUILD_DIR/$PACKAGE --depth 1 || git clone $YNH_SOURCE/$PACKAGE -b $YNH_DEBIAN $YNH_BUILD_DIR/$PACKAGE --depth 1 || git clone $YNH_SOURCE/$PACKAGE $YNH_BUILD_DIR/$PACKAGE --depth 1
    - DEBIAN_FRONTEND=noninteractive apt --assume-yes -o Dpkg::Options::="--force-confold" build-dep $YNH_BUILD_DIR/$PACKAGE
    - *build_script

build-moulinette:
  extends: .build-stage
  variables:
    PACKAGE: "moulinette"
  script:
    - git clone $YNH_SOURCE/$PACKAGE -b $CI_COMMIT_REF_NAME $YNH_BUILD_DIR/$PACKAGE --depth 1 || git clone $YNH_SOURCE/$PACKAGE -b $YNH_DEBIAN $YNH_BUILD_DIR/$PACKAGE --depth 1 || git clone $YNH_SOURCE/$PACKAGE $YNH_BUILD_DIR/$PACKAGE --depth 1
    - DEBIAN_FRONTEND=noninteractive apt --assume-yes -o Dpkg::Options::="--force-confold" build-dep $YNH_BUILD_DIR/$PACKAGE
    - *build_script
