########################################
# LINTER
########################################
# later we must fix lint and format-check jobs and remove "allow_failure"

actionsmap:
  stage: lint
  image: "before-install"
  needs: []
  script:
    - python -c 'import yaml; yaml.safe_load(open("share/actionsmap.yml"))'
    - python -c 'import yaml; yaml.safe_load(open("share/actionsmap-portal.yml"))'

lint311:
  stage: lint
  image: "before-install"
  needs: []
  allow_failure: true
  script:
    - tox -e py311-lint

invalidcode311:
  stage: lint
  image: "before-install"
  needs: []
  script:
    - tox -e py311-invalidcode

mypy:
  stage: lint
  image: "before-install"
  needs: []
  script:
    - tox -e py311-mypy

i18n-keys:
  stage: lint
  needs: []
  script:
    - python3 maintenance/missing_i18n_keys.py --check
