.install_debs: &install_debs
    - DEBIAN_FRONTEND=noninteractive SUDO_FORCE_REMOVE=yes apt --assume-yes -o Dpkg::Options::="--force-confold" --allow-downgrades install ${CI_PROJECT_DIR}/*.deb

.test-stage:
  stage: test
  image: "core-tests"
  variables:
    PYTEST_ADDOPTS: "--color=yes"
  before_script:
    - *install_debs
  cache:
    paths: 
      - src/tests/apps
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  needs:
      - job: build-yunohost
        artifacts: true
      - job: build-ssowat
        artifacts: true
      - job: build-moulinette
        artifacts: true
      - job: upgrade

########################################
# TESTS
########################################

test-helpers2:
  extends: .test-stage
  script:
    - cd tests
    - bash test_helpers.sh

test-helpers2.1:
  extends: .test-stage
  script:
    - cd tests
    - bash test_helpers.sh 2.1

test-domains:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_domains.py

test-dns:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_dns.py

test-apps:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_apps.py

test-appscatalog:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_app_catalog.py

test-appurl:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_appurl.py

test-questions:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_questions.py

test-app-config:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_app_config.py

test-app-resources:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_app_resources.py

test-changeurl:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_changeurl.py

test-backuprestore:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_backuprestore.py

test-permission:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_permission.py

test-settings:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_settings.py

test-user-group:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_user-group.py

test-regenconf:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_regenconf.py

test-service:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_service.py

test-ldapauth:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_ldapauth.py

test-sso-and-portalapi:
  extends: .test-stage
  script:
    - python3 -m pytest src/tests/test_sso_and_portalapi.py
